### ISSUE TITLE
future of rtox

### ISSUE THREAD

**Issue by ssbarnea** [dolph/rtox#3]
@dolph First, let me thank you for writing rtox a couple of years ago. I found it by looking exactly for the same thing and I was planning to implement something similar myself in case I didn't find something usable. Luckily, rtox was usable.

I encountered few bugs and fixed them, planning to address few more. Not sure if you observed by I also published the package on pypi and added travis CI.

The currently maintained version is hosted under [pycontribs](https://github.com/pycontribs/rtox) github organization now as I want to be sure that there is always more than one possible maintainer.

I would like to add you there and also on pypi, so you can also perform maintenance and releases. Is this ok?

**Comment by dolph** [comment]
I'm glad you found it useful, and happy you found ways to improve it! (and I'm sorry for the belated reply - I'm not sure I how I missed this!) It was super handy for saving battery on my laptop. If you'd still like to add me as a backup maintainer, I'd be happy to oblige. However, I don't expect to be using (or developing) rtox on my own in the immediate future - it's just not necessary for my current job.

I'll update the README to point to your fork! Thanks again.

**Comment by ssbarnea** [comment]
@dolph Sure, added you to both github and pypi. Always good to have backups and to avoid the need of forking. Safe to archive this repo and continue there, not that we would have many things to update anyway.

BTW, I recently had a more generic approach that is not limited to tox use and ended up doing https://pypi.org/project/rmux/ have a look, maybe we want to continue colaborating on that one.
